# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Rajat Verma
tagline:          'Personal website'
description:      'Ph.D. Candidate, <br>Data and Design Enthusiast'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rajat Verma'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/rvanxer/rvanxer.github.io
